name: Send Monthly Invoice

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs on the 1st of every month at midnight UTC
  workflow_dispatch:      # This enables manual triggering


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Pandoc and wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc wkhtmltopdf

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      env:
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python make-invoice.py